[package]
name = "add"
version = "0.3.0"
edition = "2024"
publish = false

description = "A simple crate that adds two numbers"
license = "MIT"
repository = "https://github.com/prashant1k99/test-crate-tag"

[dependencies]
