[workspace]
workspace = true

[release]
publish = false

push = true
tag = true
sign-tag = false

tag-format = "{{package_name}}-v{{version}}"
tag-message = "Release {{package_name}} version {{version}}"
commit-message = "Release {{package_name}} version {{version}}"

pre-release-hook = [
  "cargo test --package {{crate_name}}",
  "cargo doc --no-deps --package {{crate_name}}",
]
